### ISSUE TITLE
[New Issue]: Seeing Two collaborative sessions warning occasionally when creating a new file

### ISSUE THREAD

**Issue by jzhang20133** [jupyterlab/jupyter-collaboration#245]
## Description

We are occasionally observing an error dialog when opening up a new file that says there are two collaborative sessions are created for this file.
![Screenshot 2024-02-26 at 11 42 20 AM (1)](https://github.com/jupyterlab/jupyter-collaboration/assets/4554746/af1e5ce3-d34f-4a39-aee7-9b83bb42181a)

## Reproduce

We haven't found a way to reproduce this reliably. It feels a bit flaky, though I have some suspicion on where this is coming from, mentioned below. Here is are the series of logs we need:

```
[I 2024-02-26 11:40:01.627 ServerApp] Request for Y document 'TestRTCWithFolder/Untitled.ipynb' with room ID: 9bc89a74-323a-411f-96b4-bf47260a909f
[I 2024-02-26 11:40:01.765 YDocExtension] Creating FileLoader for: TestRTCWithFolder/Untitled.ipynb
[E 2024-02-26 11:40:01.766 ServerApp] Uncaught exception GET /api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_collaboration/handlers.py", line 105, in prepare
        await self._websocket_server.start_room(self.room)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/pycrdt_websocket/websocket_server.py", line 88, in start_room
        await self._task_group.start(room.start)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 800, in start
        task = self._spawn(func, args, name, future)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 752, in _spawn
        raise RuntimeError(
    RuntimeError: This task group is not active; no new tasks can be started.
[E 2024-02-26 11:40:01.772 ServerApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_collaboration/handlers.py", line 105, in prepare
        await self._websocket_server.start_room(self.room)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/pycrdt_websocket/websocket_server.py", line 88, in start_room
        await self._task_group.start(room.start)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 800, in start
        task = self._spawn(func, args, name, future)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 752, in _spawn
        raise RuntimeError(
    RuntimeError: This task group is not active; no new tasks can be started.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1298, in send_error
        self.write_error(status_code, **kwargs)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 718, in write_error
        html = self.render_template("%s.html" % status_code, **ns)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 644, in render_template
        ns.update(self.template_namespace)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 654, in template_namespace
        logged_in=self.logged_in,
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 196, in logged_in
        user = self.current_user
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1424, in current_user
        self._current_user = self.get_current_user()
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 175, in get_current_user
        raise RuntimeError(msg)
    RuntimeError: Calling `YDocWebSocketHandler.get_current_user()` directly is deprecated in jupyter-server 2.0. Use `self.current_user` instead (works in all versions).
[E 2024-02-26 11:40:01.775 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
    }
[E 2024-02-26 11:40:01.775 ServerApp] 500 GET /api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3 (@127.0.0.1) 9.74ms referer=None
[I 2024-02-26 11:40:01.791 YDocExtension] Watching file: TestRTCWithFolder/Untitled.ipynb
[E 2024-02-26 11:40:02.076 ServerApp] Uncaught exception GET /api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_collaboration/handlers.py", line 105, in prepare
        await self._websocket_server.start_room(self.room)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/pycrdt_websocket/websocket_server.py", line 88, in start_room
        await self._task_group.start(room.start)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 800, in start
        task = self._spawn(func, args, name, future)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 752, in _spawn
        raise RuntimeError(
    RuntimeError: This task group is not active; no new tasks can be started.
[E 2024-02-26 11:40:02.077 ServerApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_collaboration/handlers.py", line 105, in prepare
        await self._websocket_server.start_room(self.room)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/pycrdt_websocket/websocket_server.py", line 88, in start_room
        await self._task_group.start(room.start)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 800, in start
        task = self._spawn(func, args, name, future)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 752, in _spawn
        raise RuntimeError(
    RuntimeError: This task group is not active; no new tasks can be started.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1298, in send_error
        self.write_error(status_code, **kwargs)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 718, in write_error
        html = self.render_template("%s.html" % status_code, **ns)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 644, in render_template
        ns.update(self.template_namespace)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 654, in template_namespace
        logged_in=self.logged_in,
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 196, in logged_in
        user = self.current_user
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1424, in current_user
        self._current_user = self.get_current_user()
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 175, in get_current_user
        raise RuntimeError(msg)
    RuntimeError: Calling `YDocWebSocketHandler.get_current_user()` directly is deprecated in jupyter-server 2.0. Use `self.current_user` instead (works in all versions).
[E 2024-02-26 11:40:02.077 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
    }
[E 2024-02-26 11:40:02.077 ServerApp] 500 GET /api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3 (@127.0.0.1) 2.57ms referer=None
[I 2024-02-26 11:40:02.116 YDocExtension] Processed 18 Y patches in one minute
[I 2024-02-26 11:40:02.116 YDocExtension] Connected Y users: 2
[E 2024-02-26 11:40:02.570 ServerApp] Uncaught exception GET /api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_collaboration/handlers.py", line 105, in prepare
        await self._websocket_server.start_room(self.room)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/pycrdt_websocket/websocket_server.py", line 88, in start_room
        await self._task_group.start(room.start)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 800, in start
        task = self._spawn(func, args, name, future)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 752, in _spawn
        raise RuntimeError(
    RuntimeError: This task group is not active; no new tasks can be started.
[E 2024-02-26 11:40:02.571 ServerApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_collaboration/handlers.py", line 105, in prepare
        await self._websocket_server.start_room(self.room)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/pycrdt_websocket/websocket_server.py", line 88, in start_room
        await self._task_group.start(room.start)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 800, in start
        task = self._spawn(func, args, name, future)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 752, in _spawn
        raise RuntimeError(
    RuntimeError: This task group is not active; no new tasks can be started.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1298, in send_error
        self.write_error(status_code, **kwargs)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 718, in write_error
        html = self.render_template("%s.html" % status_code, **ns)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 644, in render_template
        ns.update(self.template_namespace)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 654, in template_namespace
        logged_in=self.logged_in,
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 196, in logged_in
        user = self.current_user
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1424, in current_user
        self._current_user = self.get_current_user()
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 175, in get_current_user
        raise RuntimeError(msg)
    RuntimeError: Calling `YDocWebSocketHandler.get_current_user()` directly is deprecated in jupyter-server 2.0. Use `self.current_user` instead (works in all versions).
[E 2024-02-26 11:40:02.572 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
    }
[E 2024-02-26 11:40:02.572 ServerApp] 500 GET /api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3 (@127.0.0.1) 2.35ms referer=None
[I 2024-02-26 11:40:02.794 ServerApp] Out-of-band changes. Overwriting the content in room json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f
[E 2024-02-26 11:40:03.411 ServerApp] Uncaught exception GET /api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_collaboration/handlers.py", line 105, in prepare
        await self._websocket_server.start_room(self.room)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/pycrdt_websocket/websocket_server.py", line 88, in start_room
        await self._task_group.start(room.start)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 800, in start
        task = self._spawn(func, args, name, future)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 752, in _spawn
        raise RuntimeError(
    RuntimeError: This task group is not active; no new tasks can be started.
[E 2024-02-26 11:40:03.412 ServerApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_collaboration/handlers.py", line 105, in prepare
        await self._websocket_server.start_room(self.room)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/pycrdt_websocket/websocket_server.py", line 88, in start_room
        await self._task_group.start(room.start)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 800, in start
        task = self._spawn(func, args, name, future)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 752, in _spawn
        raise RuntimeError(
    RuntimeError: This task group is not active; no new tasks can be started.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1298, in send_error
        self.write_error(status_code, **kwargs)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 718, in write_error
        html = self.render_template("%s.html" % status_code, **ns)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 644, in render_template
        ns.update(self.template_namespace)
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 654, in template_namespace
        logged_in=self.logged_in,
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 196, in logged_in
        user = self.current_user
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/tornado/web.py", line 1424, in current_user
        self._current_user = self.get_current_user()
      File "/Users/jialinzhang/miniconda3/envs/jlab4-fresh/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 175, in get_current_user
        raise RuntimeError(msg)
    RuntimeError: Calling `YDocWebSocketHandler.get_current_user()` directly is deprecated in jupyter-server 2.0. Use `self.current_user` instead (works in all versions).
[E 2024-02-26 11:40:03.413 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
    }
[E 2024-02-26 11:40:03.413 ServerApp] 500 GET /api/collaboration/room/json:notebook:9bc89a74-323a-411f-96b4-bf47260a909f?sessionId=76415e06-5e42-460d-9356-402da6f62da3 (@127.0.0.1) 2.80ms referer=None
```

## Expected behavior

Dialog should not be popped up when one user is accessing. 

## Context

Suspects

FileLoaderMapper dict is not thread safe. When there are concurrent calls to create file loader, two file loaders could be created and one of the file loader will be referenced from dict in FileLoaderMapper. Both file loaders could have watcher tasks running and for file loader which is not saved in dict, the last_modified field is incorrect and it will report out-of-band changes all the time.

**Comment by davidbrochart** [comment]
This should only happen when two views of the same file are opened simultaneously (even for only one user), for instance a notebook file opened with the notebook editor and with the text editor.

**Comment by martinRenou** [comment]
We've seen this flaky message too in JupyterCAD. It has been especially annoying in our visual regression tests.

Given that the end-user cannot do much about it (except pressing "Ok") I would vote for only showing a warning in the console, not in a pop-up window. Pop-up windows should probably be avoided as much as possible.

**Comment by jzhang20133** [comment]
I found another possible scenario that this could happen when user just has one view. When the first websocket request fail in [line 105 in prepare()](https://github.com/jupyterlab/jupyter-collaboration/blob/main/jupyter_collaboration/handlers.py#L105), basically if exception is thrown between line 87 to line 105. This first websocket failed.  Then another websocket is attempted to open for same file because UI will retry.  For the second websocket, in prepare() method, we will find there is an existing fileLoader for this file_id, hence the warning sign will show up when user only have one view of the file.

**Comment by davidbrochart** [comment]
Good point, could you write a test that reveals this behavior?

**Comment by krassowski** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyter-collaboration/pull/289, please reopen if it is incorrect.
