### ISSUE TITLE
Adopt AnyIO

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyter-collaboration#252]
### Problem

I'm seeing this error due to [aiosqlite](https://github.com/omnilib/aiosqlite), for instance in the [CI](https://github.com/jupyterlab/jupyter-collaboration/actions/runs/8297184676/job/22708202921?pr=251#step:7:65):
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.8\x64\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\hostedtoolcache\windows\Python\3.11.8\x64\Lib\site-packages\aiosqlite\core.py", line 120, in run
    future.get_loop().call_soon_threadsafe(set_exception, future, e)
  File "C:\hostedtoolcache\windows\Python\3.11.8\x64\Lib\asyncio\base_events.py", line 807, in call_soon_threadsafe
    self._check_closed()
  File "C:\hostedtoolcache\windows\Python\3.11.8\x64\Lib\asyncio\base_events.py", line 520, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
I also saw this kind of errors in Jupyverse, where I'm switching to [sqlite-anyio](https://github.com/davidbrochart/sqlite-anyio) ([here](https://github.com/jupyter-server/jupyverse/pull/388)).

### Proposed Solution

In general, jupyter-collaboration could benefit from structured concurrency, just like pycrdt-websocket did.

**Comment by dlqqq** [comment]
Found a possibly related upstream issue: https://github.com/omnilib/aiosqlite/issues/241
