### ISSUE TITLE
Can not open existing notebooks with JupyterLab 4.2.5 and jupyter-collaboration 3

### ISSUE THREAD

**Issue by trungleduc** [jupyterlab/jupyter-collaboration#398]
## Description

When using JupyterLab 4.2.5 and jupyter-collaboration 3 together, I cannot reopen my existing notebooks

https://github.com/user-attachments/assets/6320f9fa-b8a6-4cd2-a654-38f144225118

## Reproduce

1. Install Jupyterlab 4.2.5, create a notebook
2. Install jupyter-collaboration 3, then try to open the above notebook

## Expected behavior

- I can open my old notebooks or Jupyterlab 4.2.5 and jupyter-collaboration 3 cannot be installed together

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jtpio** [comment]
For reference, installing `jupyterlab=4.2.5` and `jupyter-collaboration=3` together in a clean environment and then creating a *new* notebook seems to be working fine:

![image](https://github.com/user-attachments/assets/a5860bda-9539-4d34-ba6e-983491ffeaad)

**Comment by shawnbrown** [comment]
I've been running into this bug, too.

Out of curiosity (and since I have no sense of the internals), I was curious to see if there were any format differences or added values in the `ipynb` JSON format. I created two small files and compared them: one _before installing_ version 3.0.0 and one _after installing_.

The `ipynb` files are exactly the same (save for the `id` hashes) but one opens and the other does not.

> For reference, installing jupyterlab=4.2.5 and jupyter-collaboration=3 together in a clean environment and then creating a new notebook seems to be working fine:

@jtpio, I'm not sure this is always the case. When I created some sample notebooks *after* installing `jupyter-collaboration==3`,  they would sometimes give the same behavior shown in @trungleduc's video but it was not consistent.

I can't be certain, but my sense was if I created a notebook file and had it open for a while then it seemed to be good and I never encountered the bug. But if I created a short notebook file, executed a few cells, and saved it relatively quickly, then it wouldn't reopen later.

It seemed like there's something happening that takes a few seconds to complete and if I saved and close the file before that time, then I would never be able to reopen it later (and it would look just like the bug in the video).

I also tried to downgrade to `jupyter-collaboration==2.1.5` but after doing this, the file-browser tab in the left sidebar was gone. However a clean install starting with version 2.1.5 seemed to work fine for me (no file-open bug and left sidebar was fine).

**Comment by abhijeetgurle-dream11** [comment]
I had also faced similar issues and I upgraded my jupyterlab to 4.3.0. After upgrading notebooks are opening but sometimes it can take a long time to open. Issue is mentioned [here](https://github.com/datalayer/jupyter-server-nbmodel/issues/28).

**Comment by claytonparnell** [comment]
Any update on this issue? This is a major issue for us blocking existing notebooks from opening. If we just download a notebook, rename the file, and upload the renamed notebook, we see the issue in the video where the notebook completely fails to render. We can't currently upgrade to JL 4.3 because our image follows SemVer, and anyway the notebook package currently [pins](https://github.com/conda-forge/notebook-feedstock/blob/main/recipe/meta.yaml#L2) to JL<4.3.

**Comment by ellisonbg** [comment]
Is it possibly related to the reproduction that @brichet described on this issue: https://github.com/jupyterlab/jupyter-collaboration/issues/390#issuecomment-2515667136

**Comment by ellisonbg** [comment]
I was able to reproduce this by following the exact steps in the video. One extra data point though. I did see the the following in the Terminal when the notebook failed to open:

```
[E 2024-12-05 19:14:27.909 ServerApp] Error saving file: Untitled.ipynb
    TypeError("'ArrayIterator' object is not iterable")
    Traceback (most recent call last):
      File "/Users/brgrange/Notebooks/bug398/.pixi/envs/default/lib/python3.13/site-packages/jupyter_server_ydoc/rooms.py", line 285, in _maybe_save_document
        "content": self._document.source,
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/brgrange/Notebooks/bug398/.pixi/envs/default/lib/python3.13/site-packages/jupyter_ydoc/ybasedoc.py", line 90, in source
        return self.get()
               ~~~~~~~~^^
      File "/Users/brgrange/Notebooks/bug398/.pixi/envs/default/lib/python3.13/site-packages/jupyter_ydoc/ynotebook.py", line 204, in get
        cell = self.get_cell(i)
      File "/Users/brgrange/Notebooks/bug398/.pixi/envs/default/lib/python3.13/site-packages/jupyter_ydoc/ynotebook.py", line 106, in get_cell
        cell = self._ycells[index].to_py()
      File "/Users/brgrange/Notebooks/bug398/.pixi/envs/default/lib/python3.13/site-packages/pycrdt/_map.py", line 111, in to_py
        py[key] = val.to_py()
                  ~~~~~~~~~^^
      File "/Users/brgrange/Notebooks/bug398/.pixi/envs/default/lib/python3.13/site-packages/pycrdt/_array.py", line 350, in to_py
        py = [value for value in self]
                                 ^^^^
    TypeError: 'ArrayIterator' object is not iterable
```

**Comment by ellisonbg** [comment]
OK, not sure if this is the root cause of this issue, but the above traceback is due to a bug in pycrdt:

https://github.com/jupyter-server/pycrdt/issues/198

**Comment by ellisonbg** [comment]
FYI: I tried the fix to the pycrdt `ArrayIterator` locally and it doesn't seem to fix this issue, but may fix other issues.

**Comment by ellisonbg** [comment]
A few other notes:

* I am running jupyter_ydoc 3.0.2 with the streaming output fix and still seeing the issue.
* I am suspecting it may be related to the windowed rendering of cells for a couple of reasons: 1) the cell in the above screentshot are missing, just like the windowing is hiding them, 2) some of the tracebacks that I see in the browser console suggest code in the windowing logic.
* However, the problem is still there if I disable windowing in the JupyterLab settings.

**Comment by ellisonbg** [comment]
Another observation: when I delete the `.jupyter_ystore` file, the issue persists. This suggests this particular issue is different from some of the others where deleting this file resolves the issue.

**Comment by krassowski** [comment]
@ellisonbg do you have JupyterLab 4.3.1 or 4.3.2?

**Comment by ellisonbg** [comment]
This particular bug shows up with JupyterLab 4.2.5.Sent from my iPhoneOn Dec 6, 2024, at 12:35 AM, Michał Krassowski ***@***.***> wrote:﻿
@ellisonbg do you have JupyterLab 4.3.1 or 4.3.2?

**Comment by trungleduc** [comment]
> Is it possibly related to the reproduction that @brichet described on this issue: [#390 (comment)](https://github.com/jupyterlab/jupyter-collaboration/issues/390#issuecomment-2515667136)

it does not look like related, I do see the `jupyter_server_ydoc` server extension activated in the screencast above

![ydoc](https://github.com/user-attachments/assets/02fea686-0762-4278-8906-c6817e2b0324)

**Comment by davidbrochart** [comment]
I found that `jupyterlab` v4.2.5 requires [@jupyter/ydoc >=2.0.1,<3.0.0](https://github.com/jupyterlab/jupyterlab/blob/a0461257b780435e7d7e0c7044f111f616d4d719/packages/cells/package.json#L47) (the JavaScript shared models), but `jupyter-collaboration` v3.0.0 requires [jupyter-ydoc >=2.1.2,<4.0.0](https://github.com/jupyterlab/jupyter-collaboration/blob/d5da8333822f7a901efbd9fab7d1ed11e33ed551/projects/jupyter-server-ydoc/pyproject.toml#L32) (the Python shared models). Nothing prevents version 3 of the Python models to be installed in an environment with version 2 of the JavaScript models. But these models are incompatible: the cell outputs are modeled differently, which causes an infinite recursion when converting them to JSON.
I think that the root issue is that JupyterLab uses `@jupyter/ydoc` even when jupyter-collaboration is not installed. On the other hand, jupyter-collaboration doesn't depend on JupyterLab, at least not on the Python package. This seems to introduce a loose coupling between the JavaScript and the Python versions of `jupyter-ydoc`. In jupyter-collaboration v3 we wanted to support v2 or v2 of `jupyter-ydoc`:
https://github.com/jupyterlab/jupyter-collaboration/blob/22a505bef7c1206e307f3cecede94af1ac88c956/packages/docprovider/package.json#L45
https://github.com/jupyterlab/jupyter-collaboration/blob/22a505bef7c1206e307f3cecede94af1ac88c956/projects/jupyter-server-ydoc/pyproject.toml#L32
But this doesn't seem to enforce that if v2 is installed both the JavaScript and the Python sides should be v2, and if v3 is installed both the JavaScript and the Python sides should be v3.
Anyways, a workaround to have JupyterLab v4.2.5 and jupyter-collaboration v3 working together is to do:
```bash
pip install "jupyter-ydoc<3"
```

**Comment by andrii-i** [comment]
JupyteLab >= 4.3 pins ydoc js at ["@jupyter/ydoc": "^3.0.0"](https://github.com/jupyterlab/jupyterlab/blob/87cb79fe29c623f1e2f3d00e8d0d51c656ef12d4/packages/cells/package.json#L47). 

So with "jupyter_ydoc>=2.1.2,<4.0.0,!=3.0.0,!=3.0.1" pin in jupyter-collaboration python / js version mistmatch would not happen with JupyterLab >= 4.3 in new environments or environments without `jupyter_ydoc`. However it would still happen in environments where `jupyter_ydoc>=2.1.2,<3` is already installed.

**Comment by zhuzihao-hz** [comment]
I have faced similar issues with jupyterlab 4.2.5 after installing jupyter-collaboration. 

This method worked for me.


> I had also faced similar issues and I upgraded my jupyterlab to 4.3.0. After upgrading notebooks are opening but sometimes it can take a long time to open. Issue is mentioned [here](https://github.com/datalayer/jupyter-server-nbmodel/issues/28).
